
language: c

compiler:
  - clang
  - gcc

os:
  - linux
  - osx

sudo: false

env:
  global:
    - BASE_OUTDIR=$TRAVIS_BUILD_DIR/out
    - BUILD=check
    - ENABLE_COVERAGE=no
    - ENABLE_VALGRIND=no
    - secure: "rHwlRDO/xvFHScz9rCCUYVnf6okYLuSH9HMqvZPVwI/CFb9FlUnTYfXBnI0eEK/9PVrl2Q8CLxJpdUn0P7zSwcLlI1PaLWpx0W5meM4JDtYRaI4wbwNjOg2ziM20LgzEWeFSk+XvJQMuOEuW6z7T0NZl9se2MTfBfgQZs9cCH8WmMvjN2hFNXGfoROLbHtEGPo7pc0ob7WkAxQ3aJ1fm7ehCU1V7SxxrLFVWY37xrwRMeUBPLcV/F5owtZrOZFAB6burrrUy1kZhZEcrJRMrA8oFESK4cOdnpZEY5B3db3XBW1MtgFJXh+b6TbwkRIjYDgjt6OkGqAsgguaB3NJ1UENxT/S86Q6tvWRuh7E1d56IcGrb+BLF9S8KiYgr/iPfC8hmbGdV0PbLkSXL5/+03wMTmww4MwaDKq8TkMXRvuc8cdm73jxqoQhqhDxYbOr8z1zAFeCasPukE7unb7McuF85kdX1VAEcq7K70mz292BKGOVHi55KGpGf+QlXpecsjRIV7XkArK9NI1VyZDfJpsRjzBmz5K9wp08gT/bbKYuEeaQlkOk3b4qlSYGLA3HnYD0UweSYuEvux0flQoS6QAiYmTWRe5qmEVzo22L5h9x3f2+Fv93d7hwu1UAwLe5zs83YLURdzu6OQwAnk8imzya4hk3+nqU05PVFN9b65Fk="
    - MAKEJOBS=-j3

  matrix:
    - BUILD=distcheck MAKEJOBS=-j3
    - ENABLE_COVERAGE=yes
    - ENABLE_VALGRIND=yes

cache:
  apt: true

addons:
  apt:
    packages:
      - libssl-dev
      - libgmp-dev
      - libjansson-dev
      - libevent-dev
      - lcov
      - valgrind
      - libtool
      - libltdl-dev
  coverity_scan:
    project:
      name: "jgarzik/picocoin"
      description: "Build submitted via Travis CI"
    notification_email: jeff@bloq.com
    build_command_prepend: "./autogen.sh && ./configure && make -s clean"
    build_command:   "make -s check"
    branch_pattern: master

before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update && brew upgrade; fi
  - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install jansson; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install libevent; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install argp-standalone; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install openssl; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ] && [ "$ENABLE_COVERAGE" = "yes" ]; then brew install lcov; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ] && [ "$ENABLE_VALGRIND" = "yes" ]; then brew install valgrind; fi
  - if [ "$ENABLE_COVERAGE" = "yes" ]; then gem install coveralls-lcov; fi

before_script:
  - if [ -n "$USE_SHELL" ]; then export CONFIG_SHELL="$USE_SHELL"; fi
  - test -n "$USE_SHELL" && eval '"$USE_SHELL" -c "./autogen.sh"' || ./autogen.sh

script:
  - OUTDIR=$BASE_OUTDIR/$TRAVIS_PULL_REQUEST/$TRAVIS_JOB_NUMBER-$HOST
  - PICOCOIN_CONFIG_ALL="--prefix=$TRAVIS_BUILD_DIR/depends/$HOST --bindir=$OUTDIR/bin --libdir=$OUTDIR/lib"
  - ./configure --cache-file=config.cache --enable-coverage=$ENABLE_COVERAGE --enable-valgrind=$ENABLE_VALGRIND $PICOCOIN_CONFIG_ALL $PICOCOIN_CONFIG || ( cat config.log && false)
  - make -s $MAKEJOBS $GOAL || ( echo "Build failure. Verbose build follows." && make $GOAL ; false )
  - export LD_LIBRARY_PATH=$TRAVIS_BUILD_DIR/depends/$HOST/lib
  - make $MAKEJOBS $BUILD

after_success:
  - if [ "$ENABLE_COVERAGE" = "yes" ]; then lcov --compat-libtool --directory . --capture --output-file coverage.info && coveralls-lcov coverage.info; fi

